- extensions:
  - org
  mode:
    view: emacs
    edit: emacs

- mimetypes:
  - text/csv
  - text/plain
  mode:
    view: cat 
    edit: code

- mimetypes:
  - image/*
  mode:
    view: imv
    edit: gimp

- mimetypes:
  - inode/directory
  mode:
    view: ls -l {} && echo success
    edit: ls -l